server:
  port: 8001
spring:
  application:
    name: leyou-user
  datasource:
    url: jdbc:mysql://172.17.0.1:33061/leyou?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  redis:
    host: 172.17.0.1
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6666/eureka
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true  #当你获取host时，返回的不是主机名，而是ip
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
